server.servlet.session.persistent=false

spring.neo4j.uri=neo4j+s://cc7e26d5.databases.neo4j.io

spring.neo4j.authentication.username=cc7e26d5

spring.neo4j.authentication.password=ODw_Z_LTSGO5w6RuJxWriVeXkHDXLMHgJ5jRrDlsiS4

server.tomcat.basedir=target/tomcat