spring.application.name=proyecto
spring.neo4j.uri=neo4j+s://f5142b00.databases.neo4j.io
spring.neo4j.authentication.username=f5142b00
spring.neo4j.authentication.password=mEknZCMv_UD64ARlG1O74pw9LJDigL3V6uwgfNPS5O8
